[workspace]
members = ["backend"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/habedi/template-rust-web-app"
authors = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
strip = "debuginfo"
codegen-units = 1
lto = true

[profile.test]
debug = true
